doct/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from doct.app import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^$', 'doct.app.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^task/$', views.new_task, name='new_task'),
    url(r'^task/(?P<pk>[0-9]+)/$', views.show_task, name='show_task'),
    url(r'^task/update/(?P<pk>[0-9]+)/$', views.update_task, name='update_task'),
    url(r'^task/new/$', views.new_task, name='new_task'),
    url(r'^list/$', RedirectView.as_view(url='/list/1', permanent=False), name='index'),
    url(r'^list/(?P<pk>[0-9]+)$', views.list_task, name='list_task'),
    url(r'^contribute/(?P<pk>[0-9]+)/$', views.contribute_task, name='contribute_task'),
    url(r'^search/task/', views.search_task, name='search_task'),
)

doct/app/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255, blank=False)
    link = models.CharField(max_length=512, blank=False)
    description = models.CharField(max_length=2048, blank=False)
    # key = models.CharField(max_length=512, blank=False)

    class Meta:
        managed = True
        db_table = 'Task'
        verbose_name = "Task"
        verbose_name_plural = "Tasks"


class StatTask(models.Model):
    task = models.OneToOneField(Task)
    update_time = models.DateTimeField(auto_now=False)
    number_users = models.IntegerField(default=0)
    number_teams = models.IntegerField(default=0)
    number_hosts = models.IntegerField(default=0)
    total_credit = models.FloatField(default=0)
    update_time_db = models.DateTimeField(auto_now=True)

    class Meta:
        managed = True
        db_table = 'StatTask'
        verbose_name = "StatTask"
        verbose_name_plural = "StatsTask"


class Contribute(models.Model):
    ram = models.PositiveIntegerField(default=1024, verbose_name='RAM')
    cpu = models.PositiveIntegerField(default=2, verbose_name='CPU (number of core)')
    # gpu = models.PositiveIntegerField(default=0, verbose_name='GPU')
    disk_space = models.IntegerField(default=10, verbose_name='Disk pace (Go)')
    # email = models.CharField()
    # password = models.CharField()

doct/app/forms.py
from django import forms
from doct.app.models import Task, Contribute


class TaskForm(forms.ModelForm):
    description = forms.CharField( widget=forms.Textarea )
    class Meta:
        model = Task
        fields = ['title', 'description', 'link']


class ContributeForm(forms.ModelForm):
    class Meta:
        model = Contribute
        fields = ['ram', 'cpu', 'disk_space']

doct/app/views.py
from django.shortcuts import render
from doct.app.models import Task, StatTask
from doct.app.forms import TaskForm, ContributeForm

from django.http import HttpResponseRedirect, HttpResponse

from doct.utils import docker

# to get and parse stat
import requests
from xml.dom import minidom
from datetime import datetime, timedelta

# search task
import json

# trending project
from django.db.models import Count

def home(request):
    trending_projects = StatTask.objects.annotate(Count('number_users')).order_by('number_users')[:3]
    return render(request, 'home.html', {'trending_projects': trending_projects})

def list_task(request, pk=None):
    if pk == None or pk <= 0:
        pk = 1
    else:
        pk = int(pk)
    tasks = Task.objects.all()
    return render(request, 'list_task.html', {'tasks': tasks[(pk - 1) * 10: pk * 10], 'current_page': pk, 'number_pages': range(1, tasks.count() / 10  + 2)})

def show_task(request, pk=None):
    try:
        task = Task.objects.get(id=pk)
    except:
        return HttpResponseRedirect("/")
    stat = getStatForTask(task)
    return render(request, 'show_task.html', {'task': task, 'stat': stat})


def update_task(request, pk=None):
    try:
        task = Task.objects.get(id=pk)
    except:
        return HttpResponseRedirect("/")
    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save()
            task.save()
            return HttpResponseRedirect("/list/")
    elif pk is not None:
        form = TaskForm(instance=task)
        return render(request, 'create_task.html', {'form': form})

def new_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save()
            task.save()
            return HttpResponseRedirect("/list/")
    else:
        form = TaskForm()
    return render(request, 'create_task.html', {'form': form})

def contribute_task(request, pk=None):
    try:
        task = Task.objects.get(id=pk)

        if request.method == "POST":
            form = ContributeForm(request.POST)
            if form.is_valid():
                script = docker.generate_configuration(
                                            link=task.link,
                                            ram=form.cleaned_data['ram'],
                                            cpu=form.cleaned_data['cpu'],
                                            # gpu=form.cleaned_data['gpu'],
                                            disk_space=form.cleaned_data['disk_space'])
                return render(request, 'result_configuration.html', {'script': script})
            else:
                return render(request, 'contribute_task.html', {'task': task, 'form': form})
        else:
            form = ContributeForm()
            return render(request, 'contribute_task.html', {'task': task, 'form': form})

    except Exception, e:
        print e
        return HttpResponseRedirect("/list/")


def getStatForTask(task):
    try:
        stat = StatTask.objects.get(task=task)
        if stat.update_time_db.replace(tzinfo=None) > datetime.now() - timedelta(hours=24):
            return stat
    except Exception, e:
        print e
        stat = None

    if stat is None:
        stat = StatTask()
        stat.task = task
    try:
        link_xml = task.link
        if task.link[:-1] is not '/':
            link_xml += '/'
        link_xml += 'stats/tables.xml'
        tables_xml = requests.get(link_xml)
    except:
        return None

    if tables_xml.status_code == 200:
        try:
            xml_doc = minidom.parseString(tables_xml.content)
            timestamp = xml_doc.getElementsByTagName('update_time')[0].childNodes[0].data
            stat.update_time = datetime.fromtimestamp(float(timestamp))
            stat.number_users = xml_doc.getElementsByTagName('nusers_total')[0].childNodes[0].data
            stat.number_teams = xml_doc.getElementsByTagName('nteams_total')[0].childNodes[0].data
            stat.number_hosts = xml_doc.getElementsByTagName('nhosts_total')[0].childNodes[0].data
            stat.total_credit = xml_doc.getElementsByTagName('total_credit')[0].childNodes[0].data
        except:
            print "Error parsing"
            return None
    else:
        print "Can't fetch stats"
        return None
    stat.save()
    return stat


def search_task(request):
    try:
        if request.is_ajax():
            q = request.GET.get('term', '')
            tasks = Task.objects.filter(title__contains = q )[:20]
            results = []
            for task in tasks:
                task_json = {}
                task_json['id'] = task.id
                task_json['label'] = task.title
                task_json['value'] = task.link
                results.append(task_json)
            data = json.dumps(results)
        else:
            data = 'fail'
        mimetype = 'application/json'
        return HttpResponse(data, mimetype)
    except Exception, e:
        print e

doct/app/templates/contribute_task.html
{% extends 'template_base.html' %}

{% block content %}
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <!--<div class="clearfix"></div>-->
                <h2>{{ task.title }}</h2>
                    <form method="POST" class="post-form text-center">
                        {% csrf_token %}
                            <div class="row">
                                    <label for="id_ram">RAM:</label>
                            </div>

                            <div class="row">
                                    <input id="id_ram" min="0" name="ram" type="number" value="1024">
                            </div>

                            <br/>
                            <div class="spacer"></div>
                            <div class=row>
                                    <br/>
                                    <label for="id_cpu">CPU (number of core):</label>
                            </div>
                            <div class="row">
                                    <input id="id_cpu" min="0" name="cpu" type="number" value="2">
                            </div>
                                <!--<p>-->
                                <!--<label for="id_gpu">GPU:</label> <input id="id_gpu" min="0" name="gpu" type="number" value="0">-->
                                <!--</p>-->
                            <br/>
                            <div class="spacer"> </div>
                            <div class="row">
                                    <label for="id_disk_space">Disk pace (Go):</label>
                            </div>
                            <div class="row">
                                <input id="id_disk_space" name="disk_space" type="number" value="10">

                        <!--<div class="row">-->
                            <br/>
                            <div class="spacer"> </div>
                            <br/>
                            <br/>
                            <button type="submit" class="save btn btn-default btn-lg mbutton"> Run container !!! </button>
                        </div>
                    </form>

                <br/>
            </div>
        </div>
    </div>
{% endblock content %}

doct/app/templates/create_task.html
{% extends 'template_base.html' %}

{% block content %}
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <h2>New task</h2>
                <form method="POST" class="post-form text-center">
                    {% csrf_token %}
                    <div class="row">
                        <label for="id_title"><h4> Title: </h4></label>
                    </div>
                    <div class="row">
                        <input id="id_title" maxlength="255" name="title" type="text">
                    </div>

                    <br/>
                    <div class="spacer"></div>
                    <div class=row>
                            <label for="id_link"> <h4> Docker container path: </h4> </label> 
                    </div>
                    <div class="row">
                            <input id="id_link" maxlength="512" name="link" type="text">
                    </div>

                    <br/>
                    <div class="spacer"> </div>
                    <div class="row">
                        <label for="id_description"><h4> Description: </h4> </label> 
                    </div>
                    <div class="row">
                        <textarea cols="40" id="id_description" name="description" rows="10"></textarea>
                    </div>

                    <div class="row">
                        <div class="spacer"> </div>
                        <button type="submit" class="btn btn-default btn-lg mbutton"><span class="network-name">Save</span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

doct/app/templates/home.html
{% extends 'template_base.html' %}

{% block content %}

    <div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1 style="color: #EEEEEE">Hive Project</h1>
                        <h3>An open, docker based tool for sharing calculation</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="https://twitter.com/GaryLaurenceau" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li>
                                <a href="https://github.com/dockerparis/Hive" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div> 
    <div class="content-section-a">
        <div class="container">
            <h3>Trending projects</h3>
            <div class="row">
                {% for project in trending_projects %}
                    <div class="col-lg-4 col-sm-6">
                        <div class="clearfix"></div>
                        <h2 class="section-heading"><a href="/task/{{ project.task.link }}">{{ project.task.title }}</a></h2>
                        <p class="lead">{{ project.task.description|truncatewords:14|slice:"-4"| safe }}...</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


    <div class="content-section-a">
        <div class="container text-center">
            <div class="row">
                <!--<hr class="section-heading-spacer">-->
                <div class="clearfix"></div>
                <h2 class="section-heading"> Upload your container ! </h2>
                <a href="/task/new/" class="btn btn-default btn-lg mbutton"> <span class="network-name">Upload</span> </a>
            </div>
        </div>
    </div>

{% endblock content %}

doct/app/templates/list_task.html
{% extends 'template_base.html' %}

{% block content %}
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h2> Task List </h2>
                </div>

                <!--Search box-->
                <div class="col-lg-4" style="margin-bottom: 3px;">
                    <div class="ui-widget" style="margin-top:30px; height: 30px;">
                      <input id="tasks_searck">
                    </div>
                </div>
                </div>

                {% for task in tasks %}
                    <div class="row">
                        <h3 class="col-lg-8"><a href="/task/{{task.pk}}">{{ task.title }}</a></h3>
                        <div class="col-lg-4" style="margin-bottom: 3px">
                            <a  href="/contribute/{{task.pk}}"
                                    class="btn btn-default btn-small mbutton"
                                    style="margin-top: 14px; margin-left: 64px;">
                                <span class="network-name">
                                    Contribute
                                </span>
                            </a>
                        </div>
                    </div>
                    <p> {{ task.description|truncatewords:14|slice:"-4"|safe }}... </p>
                {% endfor %}
            </div>
            <div style="width: 100%; text-align: center;">
                {% for i in number_pages %}
                    {% if i == current_page %}
                        <a href="/list/{{i}}" style="text-decoration: underline;">{{i}}</a>
                    {% else %}
                        <a href="/list/{{i}}">{{i}}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

doct/app/templates/result_configuration.html
{% extends 'template_base.html' %}

{% block content %}
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <!--<div class="clearfix"></div>-->
                <script type="text/javascript" src="{{ STATIC_URL }}js/download.js"></script>

                <h2>Script to execute</h2>
                <textarea rows="20" cols="150" id="script">{{ script }}</textarea>
                    <br/>
                <button onclick="saveTextAsFile()">Download file</button>
                <br/>
            </div>
        </div>
    </div>
{% endblock content %}

doct/app/templates/show_task.html
{% extends 'template_base.html' %}

{% block content %}
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <h2 class="col-lg-8"><a href="{{ task.link }}">{{ task.title }}</a></h3>
                <div class="col-lg-4" style="margin-bottom: 3px;">
                    <a  href="/contribute/{{task.pk}}"
                            class="btn btn-default btn-small mbutton"
                            style="margin-top: 14px;">
                        <span class="network-name">
                            Contribute
                        </span>
                    </a>
                </div>
            </div>
            <hr>
            <div>
                <p> {{ task.description|safe }}</p>
            </div>
            <p>Update time: {{ stat.update_time }}</p><br/>
            <p>Number users: {{ stat.number_users }}</p><br/>
            <p>Number teams: {{ stat.number_teams }}</p><br/>
            <p>Number hosts: {{ stat.number_hosts }}</p><br/>
            <p>Total credit: {{ stat.total_credit }}</p><br/>
        </div>
    </div>
{% endblock content %}

doct/app/templates/template_base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Hive Project</title>

        <!-- Bootstrap Core CSS -->
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="/static/css/landing-page.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand mbrand" id="mbrand" href="/">Hive Project</a>
                </div>


                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="/list/">Project list</a>
                        </li>
                        <li>
                            <a href="/task/new/">New project</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>

        <div class="banner">

            <div class="container">

                <div class="row">
                    <div class="col-lg-6">
                        <h2 style="color: #EEEEEE">Connect to hive Project</h2>
                    </div>
                    <div class="col-lg-6">
                        <ul class="list-inline banner-social-buttons">
                            <li>
                                <a href="https://twitter.com/GaryLaurenceau" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li>
                                <a href="https://github.com/dockerparis/Hive" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <!--<li>-->
                                <!--<a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>-->
                            <!--</li>-->
                        </ul>
                    </div>
                </div>

            </div>
            <!-- /.container -->

        </div>
        <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-inline">
                            <li>
                                <a href="#home">Home</a>
                            </li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li>
                                <a href="/list/">Project list</a>
                            </li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li>
                                <a href="/task/new/">New project</a>
                            </li>
                        </ul>
                        <p class="copyright text-muted small">Copyright &copy; Hive Project 2014. All Rights Reserved</p>
                    </div>
                </div>
            </div>
        </footer>


        <!-- jQuery -->
        <script src="/static/js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="/static/js/bootstrap.min.js"></script>

        <!--Search box-->
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/static/js/search.js" type="text/javascript"></script>

    </body>
</html>